version: "3"

services:
  sprinbatch2:
    image: "benas/bootiful-job:latest"
    expose:
      - "8080"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sprinbatch2
    ports:
      - "4000:4000"
